### ISSUE TITLE
CORS header missing

### ISSUE THREAD

**Issue by freitasskeeled** [Ziggeo/vue-ziggeo#6] opened 2018-04-23 14:43 UTC
Hey there,

So it turns out that the problem that we were having with the attempts is related with a request being blocked from the browser because of a missing header 'Access-Control-Allow-Origin' (CORS).

Can you please check and confirm?

There is not much more information to share. The behaviour is very weird and we cannot find what is the triggering factor here. It happens sometimes only.

[EDIT] Request being blocked: 
https://api-eu-west-1.ziggeo.com/embed/v1/applications/{redacted}/scitylana/kcart?_wrapstatus=true&_nocache={redacted}

Thank you.

**Comment by freitasskeeled** [comment] 2018-04-23 16:53
I have more details on this but I'm not sure I can post them here. Can one of the maintainers provide an email so we can get in touch? Thanks!

**Comment by Bane-D** [comment] 2018-04-23 17:01
Hi,

Glad to hear that you have more details. Can you please send it to our support email - support@ziggeo.com ? I will be on a look out for it and pass the details to right people.

PS: If you make the same subject: "CORS header missing #6" it will be super easy to spot right away, however it is not a requirement :)

PS: The endpoint you have mentioned is actually our analytics endpoint and it will be called in a way that does not interrupt the other code on the page, so even if there is an error with it, it will just fail for it self. Still of course it should not fail, whatever the cause.

Regards,
Bane

**Comment by freitasskeeled** [comment] 2018-04-23 17:15
Thank you for the quick reply.

I've already sent you the email with some extra details.

Regards,
Freitas

**Comment by Bane-D** [comment] 2018-04-23 17:25
Hi Freitas,

Thank you for the email and included screenshots.

Looking at it I see what is happening. We are working on resolving these 502 Bad Gateway errors and they are actually the cause of the CORS message that you get.

This seems to be happening from time to time due to the quantity of the analytic requests going into our servers within given timeframe (global quantity not specific to the application).

Now the internal workings of those servers are actually causing from time to time the 502 to happen on Amazon side (where we have those servers).

Since Amazon servers reply with the 502 error, we can not actually change those headers, so the error comes from the (for us) non CORS friendly server and that is why browser complains.

Having that said we never noticed or got reports that the same was causing issues with the rest of the system. Of course it does not look nice and does not work as we want it, and it will be sorted out.

I do just want to check if by any chance you were experiencing any issues in your website / setup due to this?

Regards,
Bane

**Comment by freitasskeeled** [comment] 2018-04-23 17:33
We are not 100% sure if this is the cause of the real problem that we are having: sometimes the Vue event is not fired (when an attempt is made) and so our application cannot sync properly and show the correct information to our users. 

Like I mention in the email, we are inclined to think that is has something to do with that blocked request because it happens every time that issue occurs and also because it happens (attempt issue) randomly (at least it looks random).

**Comment by Bane-D** [comment] 2018-04-23 17:36
OK. I believe that it would actually be a different issue in that case.

Can you please tell me what is the event that you are referring to? (if OK with you feel free to include a short snippet of code of how the event is set up, does not need to have the internal event codes shown)

Regards,
Bane

**Comment by freitasskeeled** [comment] 2018-04-23 17:45
Like I said, we already did some investigation on this and the the only conclusion (until now) was that request would be the problem. Since it has nothing to do with the process itself, we will continue to investigate and try to find the cause of the issue. If we still are not able to find/fix the issue, we will get back to you.

Regarding this github issue, like you said, it's not pretty but it's not really worrying since it has no effect in our users usage as far I can (now) tell. So you can probably close it.

Thank you for the help and quick answers. 

Best regards,
Freitas

**Comment by Bane-D** [comment] 2018-04-23 17:58
OK, then lets keep it open for now Freitas. It would be good to know if if what is happening is caused by this and in case if not that additional fixes need to be placed for good future experience.

In the same time we will keep an eye on any other reports about the same, especially for vue.

Now the reason why I asked about the events is because in our r31 we made the processing and processed events fire always: https://ziggeo.com/docs/sdks/javascript/version-history

Depending on the conditions they were not really needed to fire since in some cases the videos require processing and in some they do not. In the later case it would just skip those events.

Now in r31 and all revisions that will follow it, the same events will always fire since if they otherwise would not on their own accord, we will raise them ourselves right before raising any other events.

So something like this:
```
<ziggeo-recorder
        :apiKey="'ZIGGEO_API_KEY'"
        @processing="processingEvent"
        @processed="processedEvent"
></ziggeo-recorder>
```
..could happen to not fire every time and is the reason why I asked for the event(s) in question.

* Please note that r31 is in developer preview currently and will be released soon.

Hope this helps.

Regards,
Bane

**Comment by freitasskeeled** [comment] 2018-04-23 18:05
Seems fine!

So okay, regarding the code itself we are just using the following events
      `<ziggeo-recorder
            ........
            @verified="videoRecorded"
            @access_forbidden="accessForbidden"
            @access_granted="accessGranted">
        </ziggeo-recorder>`

And we also only use your stable versions so I don't think that could be it. 

Regards,
Freitas

**Comment by Bane-D** [comment] 2018-04-24 20:05
Hi Freitas,

Sorry for a delay.

I will first mention the stable versions. Stable is currently equal to r30. This means that in it, the processing and processed events do not fire always.

Verified event should fire each time actually as it confirms that the video can be re-transcoded.

Now `access_granted` should also fire as well as `access_forbidden`, at least for the webrtc recordings. If flash is used in most cases you can expect it to not fire at all on Flash.

With that being said, there is something else to keep in mind as well. Unfortunately we can not tell if the end user allowed just microphone, or just camera, or just screen recording, or some combination of it. When we ask for permission we get from browser either true or false and raise those events in such cases (if webrtc is doing the recording).

So if you have some events that you want to happen on the access_granted, I would suggest to instead hook the same into some other event, such as `attached` to know that embedding has been added to the DOM and then listen for the `countdown` or `recording`. This would tell you that access was granted.

Now I would also suggest adding possibly a timeout and check if in 20-30 seconds for example no event was raised, suggesting that possibly the access was not given. Allowing you to react as with the access forbidden event.

Of course this would just be for those instances when Flash fires instead of webrtc (which should be less and less),

Hope this helps :)

Regards,
Bane

**Comment by freitasskeeled** [comment] 2018-04-27 17:34
Thanks again Bane!

Just to confirm, you will keep this open because of that request failing, right?

Best regards,
Freitas

**Comment by Bane-D** [comment] 2018-04-28 12:04
Hi Freitas,

We can leave it open for that yes, however since the ticket is open on our side in our ticketing system for that, we can use this (issue) to help you sort out the issue with events.

To summarize the previous reply, the events can sometimes not fire, such as when Flash is used for recording. If that was the case in your tests, you can consider it as a non bug, rather something we can not avoid once Flash is used.

If you are using non Flash method (WebRTC) to record the video and the events are still not firing, then it is a bug.

Hope this helps.

Regards,
Bane

**Comment by freitasskeeled** [comment] 2018-10-03 09:06
Hi,

I've checked and did a few tests and it seems that the opened issue is fixed.

Thanks!

**Comment by Bane-D** [comment] 2018-10-03 20:30
Hi Freitas,

Great, thank you for your feedback. I will close this then, and just to mention the CORS one is resolved as well (we are still monitoring it).

Regards,
Bane

**Closed by Bane-D** 2018-10-03 20:30 UTC
